### ISSUE TITLE
path issue with iar project platform_async_em01grpaclk_out_series2

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#15]
CMSIS?

<group>
    <name>emlib</name>
    <file>
      <name>$PROJ_DIR$\..\..\..\platform\CMSIS\emlib\src\em_cmu.c</name>
    </file>

The issue happen on several other example that support iar IDE.

**Comment by silabs-marao** [comment]
This issue was also seen in - 

- xg21_spi_flash_read_bw_polled
- xg21_spi_flash_read_bw_dma

**Comment by silabs-marao** [comment]
This has been fixed in a6d2dc6a6f571c4277e7d04f65074f464dc36093.
