### ISSUE TITLE
minor typo for smbus clk low timeout example

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#18]
platform_i2c_smbus_scl_low_timeout/i2c_smbus_scl_low_timeout_slave/src/
**PA6**, not **PB0**.
'''
  // Route Timer0 CC0 to **PB0**
  GPIO->TIMERROUTE[0].ROUTEEN  = GPIO_TIMER_ROUTEEN_CC0PEN;
  GPIO->TIMERROUTE[0].CC0ROUTE = (SCL_PORT << _GPIO_TIMER_CC0ROUTE_PORT_SHIFT)
                    | (SCL_PIN << _GPIO_TIMER_CC0ROUTE_PIN_SHIFT);
'''

**Comment by silabs-Joe** [comment]
Fixed in a3239ec
