### ISSUE TITLE
platform_emu_temp build fail

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#5]
The example platform_emu_temp could **NOT** pass build process.
File platform_applications/platform_emu_temp/SimplicityStudio/platform_emu_temp.sls include some wrong string (like **v_4_6_7**).

the unzipped .project file has lines like:
`			<locationURI>PARENT-5-PROJECT_LOC/SiliconLabs/SimplicityStudio/v4_6_7/developer/sdks/gecko_sdk_suite/v2.7/platform/emlib/src/em_usart.c</locationURI>`

**Comment by silabs-Ruibin** [comment]
Hi Denver, Thank you for reporting this! This issue is reproduced on our side and it seems to be related to how Simplicity Studio pulls in the relative path. I am looking into this and will update the repo with the correct platform_emu_temp.sls file once it is fixed.

**Comment by silabs-Ruibin** [comment]
This is addressed
