### ISSUE TITLE
platform_xg21_efp01_feature_demo build fail

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#6]
platform_applications/platform_xg21_efp01_feature_demo/SimplicityStudio/platform_xg21_efp01_feature_demo.sls contained strange string.
<locationURI>PARENT-5-STUDIO_SDK_LOC/**v4_EFPconfig_042320**/developer/sdks/gecko_sdk_suite/v2.7/hardware/kit/common/drivers/i2cspm.c<

**Comment by silabs-Ruibin** [comment]
Hi Denver, Thank you for reporting this. I am looking into this issue.
