### ISSUE TITLE
example platform_applications/platform_sleeptimer_series_2/periodic_sleeptimer_example

### ISSUE THREAD

**Issue by silabs-DenverL** [SiliconLabs/platform_applications#7]
the sls project files in folder periodic_sleeptimer_example/SimplicityStudio/ already include a main.c file. 
the source files xg21_main.c and xg22_main.c in folder periodic_sleeptimer_example/src/ was not used.

**Comment by silabs-Ruibin** [comment]
Hi Denver, Thank you for reporting this. I will check whether those two source files are necessary and will update the repo accordingly.
